import type { NetworkGroup, Plan, Project, MonthlyMetrics } from '@/types'

export const mockMetrics: MonthlyMetrics = {
  plansAnalysed: 23,
  totalLinear: 847,
  timeSaved: 52,
  activeProjects: 4,
}

export const mockProjects: Project[] = [
  {
    id: 'gare-du-nord',
    name: 'Rénovation Gare du Nord',
    client: 'VINCI Construction',
    status: 'en_cours',
    lastAnalysisAt: 'il y a 2 jours',
    plansCount: 14,
    totalLinear: 847,
  },
  {
    id: 'hopital-lariboisiere',
    name: 'Extension Hôpital Lariboisière',
    client: 'AP-HP',
    status: 'termine',
    lastAnalysisAt: 'il y a 5 jours',
    plansCount: 12,
    totalLinear: 1423,
  },
  {
    id: 'tour-montparnasse',
    name: 'Réhabilitation Tour Montparnasse',
    client: 'Altarea Cogedim',
    status: 'en_cours',
    lastAnalysisAt: 'il y a 1 jour',
    plansCount: 6,
    totalLinear: 312,
  },
  {
    id: 'usine-saint-nazaire',
    name: 'Usine Naval Groupe St-Nazaire',
    client: 'Naval Groupe',
    status: 'en_attente',
    lastAnalysisAt: 'il y a 8 jours',
    plansCount: 0,
    totalLinear: 0,
  },
  {
    id: 'metro-ligne-15',
    name: 'Grand Paris Express — Ligne 15',
    client: 'Société du Grand Paris',
    status: 'termine',
    lastAnalysisAt: 'il y a 12 jours',
    plansCount: 10,
    totalLinear: 2840,
  },
  {
    id: 'data-center-saclay',
    name: 'Data Center Paris-Saclay',
    client: 'Equinix France',
    status: 'en_cours',
    lastAnalysisAt: "aujourd'hui",
    plansCount: 9,
    totalLinear: 498,
  },
]

// ─── Network group factories ──────────────────────────────────────────────────
// Each function returns a fresh copy with unique IDs

function waterNetworks(pfx: string, ecTotal: number, efTotal: number): NetworkGroup[] {
  return [
    {
      id: `${pfx}-ec`,
      type: 'eau_chaude',
      isSelected: false,
      confidence: 0.94,
      items: [
        { id: `${pfx}-ec-1`, label: 'DN 25', quantity: +(ecTotal * 0.46).toFixed(1), elbows: Math.round(ecTotal * 0.12), unit: 'ml' },
        { id: `${pfx}-ec-2`, label: 'DN 40', quantity: +(ecTotal * 0.33).toFixed(1), elbows: Math.round(ecTotal * 0.07), unit: 'ml' },
        { id: `${pfx}-ec-3`, label: 'DN 50', quantity: +(ecTotal * 0.21).toFixed(1), elbows: Math.round(ecTotal * 0.04), unit: 'ml' },
      ],
      bbox: { x: 0.04, y: 0.04, width: 0.46, height: 0.78 },
    },
    {
      id: `${pfx}-ef`,
      type: 'eau_froide',
      isSelected: false,
      confidence: 0.91,
      items: [
        { id: `${pfx}-ef-1`, label: 'DN 25', quantity: +(efTotal * 0.55).toFixed(1), elbows: Math.round(efTotal * 0.10), unit: 'ml' },
        { id: `${pfx}-ef-2`, label: 'DN 40', quantity: +(efTotal * 0.45).toFixed(1), elbows: Math.round(efTotal * 0.06), unit: 'ml' },
      ],
      bbox: { x: 0.06, y: 0.06, width: 0.42, height: 0.74 },
    },
  ]
}

function flocageNetwork(pfx: string, total: number): NetworkGroup[] {
  return [
    {
      id: `${pfx}-fl`,
      type: 'flocage',
      isSelected: false,
      confidence: 0.89,
      items: [
        { id: `${pfx}-fl-1`, label: 'DN 50',  quantity: +(total * 0.42).toFixed(1), elbows: Math.round(total * 0.09), unit: 'ml' },
        { id: `${pfx}-fl-2`, label: 'DN 80',  quantity: +(total * 0.35).toFixed(1), elbows: Math.round(total * 0.06), unit: 'ml' },
        { id: `${pfx}-fl-3`, label: 'DN 100', quantity: +(total * 0.23).toFixed(1), elbows: Math.round(total * 0.04), unit: 'ml' },
      ],
      bbox: { x: 0.30, y: 0.04, width: 0.14, height: 0.82 },
    },
  ]
}

function airNetworks(pfx: string, soufflage: number, reprise: number, ventilos: number): NetworkGroup[] {
  return [
    {
      id: `${pfx}-gs`,
      type: 'gaine_soufflage',
      isSelected: false,
      confidence: 0.96,
      items: [
        { id: `${pfx}-gs-1`, label: '400×300', quantity: +(soufflage * 0.60).toFixed(1), elbows: Math.round(soufflage * 0.11), unit: 'ml' },
        { id: `${pfx}-gs-2`, label: '600×400', quantity: +(soufflage * 0.40).toFixed(1), elbows: Math.round(soufflage * 0.07), unit: 'ml' },
      ],
      bbox: { x: 0.38, y: 0.04, width: 0.58, height: 0.36 },
    },
    {
      id: `${pfx}-gr`,
      type: 'gaine_reprise',
      isSelected: false,
      confidence: 0.88,
      items: [
        { id: `${pfx}-gr-1`, label: '500×350', quantity: +(reprise * 0.65).toFixed(1), elbows: Math.round(reprise * 0.09), unit: 'ml' },
        { id: `${pfx}-gr-2`, label: '700×500', quantity: +(reprise * 0.35).toFixed(1), elbows: Math.round(reprise * 0.05), unit: 'ml' },
      ],
      bbox: { x: 0.38, y: 0.42, width: 0.58, height: 0.36 },
    },
    {
      id: `${pfx}-vt`,
      type: 'ventilateurs',
      isSelected: false,
      confidence: 0.99,
      items: [
        { id: `${pfx}-vt-1`, label: 'Unité', quantity: ventilos, unit: 'u' },
      ],
      bbox: { x: 0.68, y: 0.62, width: 0.28, height: 0.26 },
    },
  ]
}

function fullNetworks(pfx: string, ec: number, ef: number, fl: number, gs: number, gr: number, vt: number): NetworkGroup[] {
  return [
    ...waterNetworks(pfx, ec, ef),
    ...flocageNetwork(pfx, fl),
    ...airNetworks(pfx, gs, gr, vt),
  ]
}

// ─── Export reference network groups (for workspace default) ─────────────────
export const mockNetworkGroups: NetworkGroup[] = fullNetworks('demo', 97, 79, 55, 37, 17, 4)

// ─── PLANS ───────────────────────────────────────────────────────────────────

export const mockPlans: Plan[] = [

  // ════════════════════════════════════════════════════════════════════════════
  // 1. RÉNOVATION GARE DU NORD — Calorifuge (EC + EF + Flocage)   14 plans
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'gdn-ss1-a',
    projectId: 'gare-du-nord',
    name: 'SS-1A',
    floor: 'Sous-sol 1',
    floorOrder: -1,
    status: 'termine',
    totalLinear: 112,
    analyzedAt: 'il y a 6 jours',
    networkGroups: [
      ...waterNetworks('gdn-ss1a', 64, 48),
      ...flocageNetwork('gdn-ss1a', 38),
    ],
  },
  {
    id: 'gdn-ss1-b',
    projectId: 'gare-du-nord',
    name: 'SS-1B',
    floor: 'Sous-sol 1',
    floorOrder: -1,
    status: 'termine',
    totalLinear: 98,
    analyzedAt: 'il y a 6 jours',
    networkGroups: [
      ...waterNetworks('gdn-ss1b', 57, 41),
      ...flocageNetwork('gdn-ss1b', 30),
    ],
  },
  {
    id: 'gdn-rdc-a',
    projectId: 'gare-du-nord',
    name: 'RDC-A',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 134,
    analyzedAt: 'il y a 5 jours',
    networkGroups: [
      ...waterNetworks('gdn-rdca', 78, 56),
      ...flocageNetwork('gdn-rdca', 44),
    ],
  },
  {
    id: 'gdn-rdc-b',
    projectId: 'gare-du-nord',
    name: 'RDC-B',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 118,
    analyzedAt: 'il y a 5 jours',
    networkGroups: [
      ...waterNetworks('gdn-rdcb', 69, 49),
      ...flocageNetwork('gdn-rdcb', 36),
    ],
  },
  {
    id: 'gdn-r1-a',
    projectId: 'gare-du-nord',
    name: 'R+1A',
    floor: 'R+1',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 143,
    analyzedAt: 'il y a 4 jours',
    networkGroups: [
      ...waterNetworks('gdn-r1a', 82, 61),
      ...flocageNetwork('gdn-r1a', 48),
    ],
  },
  {
    id: 'gdn-r1-b',
    projectId: 'gare-du-nord',
    name: 'R+1B',
    floor: 'R+1',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 138,
    analyzedAt: 'il y a 4 jours',
    networkGroups: [
      ...waterNetworks('gdn-r1b', 79, 59),
      ...flocageNetwork('gdn-r1b', 42),
    ],
  },
  {
    id: 'gdn-r1-c',
    projectId: 'gare-du-nord',
    name: 'R+1C',
    floor: 'R+1',
    floorOrder: 1,
    status: 'en_cours',
    totalLinear: 0,
    networkGroups: [
      ...waterNetworks('gdn-r1c', 74, 54),
      ...flocageNetwork('gdn-r1c', 39),
    ],
  },
  {
    id: 'gdn-r2-a',
    projectId: 'gare-du-nord',
    name: 'R+2A',
    floor: 'R+2',
    floorOrder: 2,
    status: 'en_cours',
    totalLinear: 0,
    networkGroups: [
      ...waterNetworks('gdn-r2a', 68, 50),
      ...flocageNetwork('gdn-r2a', 35),
    ],
  },
  {
    id: 'gdn-r2-b',
    projectId: 'gare-du-nord',
    name: 'R+2B',
    floor: 'R+2',
    floorOrder: 2,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'gdn-r3',
    projectId: 'gare-du-nord',
    name: 'R+3',
    floor: 'R+3',
    floorOrder: 3,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'gdn-r4',
    projectId: 'gare-du-nord',
    name: 'R+4',
    floor: 'R+4',
    floorOrder: 4,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'gdn-r5',
    projectId: 'gare-du-nord',
    name: 'R+5',
    floor: 'R+5',
    floorOrder: 5,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'gdn-r6',
    projectId: 'gare-du-nord',
    name: 'R+6',
    floor: 'R+6',
    floorOrder: 6,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'gdn-toiture',
    projectId: 'gare-du-nord',
    name: 'Toiture',
    floor: 'Toiture',
    floorOrder: 999,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 2. EXTENSION HÔPITAL LARIBOISIÈRE — Flocage   12 plans
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'hlb-ss2',
    projectId: 'hopital-lariboisiere',
    name: 'SS-2',
    floor: 'Sous-sol 2',
    floorOrder: -2,
    status: 'termine',
    totalLinear: 98,
    analyzedAt: 'il y a 8 jours',
    networkGroups: flocageNetwork('hlb-ss2', 98),
  },
  {
    id: 'hlb-ss1',
    projectId: 'hopital-lariboisiere',
    name: 'SS-1',
    floor: 'Sous-sol 1',
    floorOrder: -1,
    status: 'termine',
    totalLinear: 124,
    analyzedAt: 'il y a 8 jours',
    networkGroups: [
      ...flocageNetwork('hlb-ss1', 86),
      ...waterNetworks('hlb-ss1', 24, 18),
    ],
  },
  {
    id: 'hlb-rdc-a',
    projectId: 'hopital-lariboisiere',
    name: 'RDC-A',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 148,
    analyzedAt: 'il y a 7 jours',
    networkGroups: [
      ...flocageNetwork('hlb-rdca', 102),
      ...waterNetworks('hlb-rdca', 29, 21),
    ],
  },
  {
    id: 'hlb-rdc-b',
    projectId: 'hopital-lariboisiere',
    name: 'RDC-B',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 136,
    analyzedAt: 'il y a 7 jours',
    networkGroups: [
      ...flocageNetwork('hlb-rdcb', 94),
      ...waterNetworks('hlb-rdcb', 27, 19),
    ],
  },
  {
    id: 'hlb-r1-a',
    projectId: 'hopital-lariboisiere',
    name: 'R+1A',
    floor: 'R+1',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 152,
    analyzedAt: 'il y a 6 jours',
    networkGroups: flocageNetwork('hlb-r1a', 152),
  },
  {
    id: 'hlb-r1-b',
    projectId: 'hopital-lariboisiere',
    name: 'R+1B',
    floor: 'R+1',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 144,
    analyzedAt: 'il y a 6 jours',
    networkGroups: flocageNetwork('hlb-r1b', 144),
  },
  {
    id: 'hlb-r2-a',
    projectId: 'hopital-lariboisiere',
    name: 'R+2A',
    floor: 'R+2',
    floorOrder: 2,
    status: 'termine',
    totalLinear: 138,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r2a', 138),
  },
  {
    id: 'hlb-r2-b',
    projectId: 'hopital-lariboisiere',
    name: 'R+2B',
    floor: 'R+2',
    floorOrder: 2,
    status: 'termine',
    totalLinear: 129,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r2b', 129),
  },
  {
    id: 'hlb-r3-a',
    projectId: 'hopital-lariboisiere',
    name: 'R+3A',
    floor: 'R+3',
    floorOrder: 3,
    status: 'termine',
    totalLinear: 141,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r3a', 141),
  },
  {
    id: 'hlb-r3-b',
    projectId: 'hopital-lariboisiere',
    name: 'R+3B',
    floor: 'R+3',
    floorOrder: 3,
    status: 'termine',
    totalLinear: 133,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r3b', 133),
  },
  {
    id: 'hlb-r4-a',
    projectId: 'hopital-lariboisiere',
    name: 'R+4A',
    floor: 'R+4',
    floorOrder: 4,
    status: 'termine',
    totalLinear: 127,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r4a', 127),
  },
  {
    id: 'hlb-r4-b',
    projectId: 'hopital-lariboisiere',
    name: 'R+4B',
    floor: 'R+4',
    floorOrder: 4,
    status: 'termine',
    totalLinear: 118,
    analyzedAt: 'il y a 5 jours',
    networkGroups: flocageNetwork('hlb-r4b', 118),
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 3. RÉHABILITATION TOUR MONTPARNASSE — Mixte   6 plans
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'tm-rdc',
    projectId: 'tour-montparnasse',
    name: 'RDC',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 78,
    analyzedAt: 'il y a 2 jours',
    networkGroups: fullNetworks('tm-rdc', 28, 22, 14, 18, 12, 3),
  },
  {
    id: 'tm-r1',
    projectId: 'tour-montparnasse',
    name: 'R+1',
    floor: 'R+1',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 65,
    analyzedAt: 'il y a 2 jours',
    networkGroups: fullNetworks('tm-r1', 24, 18, 11, 14, 9, 2),
  },
  {
    id: 'tm-r5',
    projectId: 'tour-montparnasse',
    name: 'R+5',
    floor: 'R+5',
    floorOrder: 5,
    status: 'en_cours',
    totalLinear: 0,
    networkGroups: fullNetworks('tm-r5', 26, 20, 12, 16, 11, 3),
  },
  {
    id: 'tm-r10',
    projectId: 'tour-montparnasse',
    name: 'R+10',
    floor: 'R+10',
    floorOrder: 10,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'tm-r15',
    projectId: 'tour-montparnasse',
    name: 'R+15',
    floor: 'R+15',
    floorOrder: 15,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'tm-toiture',
    projectId: 'tour-montparnasse',
    name: 'Toiture',
    floor: 'Toiture',
    floorOrder: 999,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 4. USINE NAVAL GROUPE — En attente, 0 plans
  // (intentionnellement vide — aucun plan ajouté)
  // ════════════════════════════════════════════════════════════════════════════

  // ════════════════════════════════════════════════════════════════════════════
  // 5. GRAND PARIS EXPRESS LIGNE 15 — Calorifuge   10 plans
  //    Organisés par station/section
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'gpe-st-denis-a',
    projectId: 'metro-ligne-15',
    name: 'Zone A',
    floor: 'Station St-Denis Pleyel',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 389,
    analyzedAt: 'il y a 14 jours',
    networkGroups: [
      ...waterNetworks('gpe-sda', 224, 165),
      ...flocageNetwork('gpe-sda', 112),
    ],
  },
  {
    id: 'gpe-st-denis-b',
    projectId: 'metro-ligne-15',
    name: 'Zone B',
    floor: 'Station St-Denis Pleyel',
    floorOrder: 1,
    status: 'termine',
    totalLinear: 342,
    analyzedAt: 'il y a 14 jours',
    networkGroups: [
      ...waterNetworks('gpe-sdb', 197, 145),
      ...flocageNetwork('gpe-sdb', 98),
    ],
  },
  {
    id: 'gpe-aubervilliers-a',
    projectId: 'metro-ligne-15',
    name: 'Zone A',
    floor: 'Station Aubervilliers',
    floorOrder: 2,
    status: 'termine',
    totalLinear: 318,
    analyzedAt: 'il y a 13 jours',
    networkGroups: [
      ...waterNetworks('gpe-aua', 183, 135),
      ...flocageNetwork('gpe-aua', 90),
    ],
  },
  {
    id: 'gpe-aubervilliers-b',
    projectId: 'metro-ligne-15',
    name: 'Zone B',
    floor: 'Station Aubervilliers',
    floorOrder: 2,
    status: 'termine',
    totalLinear: 295,
    analyzedAt: 'il y a 13 jours',
    networkGroups: [
      ...waterNetworks('gpe-aub', 170, 125),
      ...flocageNetwork('gpe-aub', 85),
    ],
  },
  {
    id: 'gpe-le-bourget-a',
    projectId: 'metro-ligne-15',
    name: 'Zone A',
    floor: 'Station Le Bourget',
    floorOrder: 3,
    status: 'termine',
    totalLinear: 276,
    analyzedAt: 'il y a 13 jours',
    networkGroups: [
      ...waterNetworks('gpe-lba', 159, 117),
      ...flocageNetwork('gpe-lba', 78),
    ],
  },
  {
    id: 'gpe-le-bourget-b',
    projectId: 'metro-ligne-15',
    name: 'Zone B',
    floor: 'Station Le Bourget',
    floorOrder: 3,
    status: 'termine',
    totalLinear: 254,
    analyzedAt: 'il y a 13 jours',
    networkGroups: [
      ...waterNetworks('gpe-lbb', 146, 108),
      ...flocageNetwork('gpe-lbb', 72),
    ],
  },
  {
    id: 'gpe-noisy-a',
    projectId: 'metro-ligne-15',
    name: 'Zone A',
    floor: 'Station Noisy-Champs',
    floorOrder: 4,
    status: 'termine',
    totalLinear: 312,
    analyzedAt: 'il y a 12 jours',
    networkGroups: [
      ...waterNetworks('gpe-nca', 180, 132),
      ...flocageNetwork('gpe-nca', 94),
    ],
  },
  {
    id: 'gpe-noisy-b',
    projectId: 'metro-ligne-15',
    name: 'Zone B',
    floor: 'Station Noisy-Champs',
    floorOrder: 4,
    status: 'termine',
    totalLinear: 287,
    analyzedAt: 'il y a 12 jours',
    networkGroups: [
      ...waterNetworks('gpe-ncb', 165, 122),
      ...flocageNetwork('gpe-ncb', 86),
    ],
  },
  {
    id: 'gpe-croissy-a',
    projectId: 'metro-ligne-15',
    name: 'Zone A',
    floor: 'Station Croissy-Champigny',
    floorOrder: 5,
    status: 'termine',
    totalLinear: 265,
    analyzedAt: 'il y a 12 jours',
    networkGroups: [
      ...waterNetworks('gpe-cra', 153, 112),
      ...flocageNetwork('gpe-cra', 80),
    ],
  },
  {
    id: 'gpe-croissy-b',
    projectId: 'metro-ligne-15',
    name: 'Zone B',
    floor: 'Station Croissy-Champigny',
    floorOrder: 5,
    status: 'termine',
    totalLinear: 243,
    analyzedAt: 'il y a 12 jours',
    networkGroups: [
      ...waterNetworks('gpe-crb', 140, 103),
      ...flocageNetwork('gpe-crb', 73),
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 6. DATA CENTER PARIS-SACLAY — Mixte   9 plans
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'dcs-ss1',
    projectId: 'data-center-saclay',
    name: 'SS-1',
    floor: 'Sous-sol 1',
    floorOrder: -1,
    status: 'termine',
    totalLinear: 89,
    analyzedAt: "aujourd'hui",
    networkGroups: fullNetworks('dcs-ss1', 32, 25, 18, 14, 9, 4),
  },
  {
    id: 'dcs-rdc-a',
    projectId: 'data-center-saclay',
    name: 'RDC-A',
    floor: 'RDC',
    floorOrder: 0,
    status: 'termine',
    totalLinear: 112,
    analyzedAt: "aujourd'hui",
    networkGroups: fullNetworks('dcs-rdca', 40, 31, 22, 19, 13, 6),
  },
  {
    id: 'dcs-rdc-b',
    projectId: 'data-center-saclay',
    name: 'RDC-B',
    floor: 'RDC',
    floorOrder: 0,
    status: 'en_cours',
    totalLinear: 0,
    networkGroups: fullNetworks('dcs-rdcb', 38, 29, 20, 17, 11, 5),
  },
  {
    id: 'dcs-r1-a',
    projectId: 'data-center-saclay',
    name: 'R+1A',
    floor: 'R+1',
    floorOrder: 1,
    status: 'en_cours',
    totalLinear: 0,
    networkGroups: fullNetworks('dcs-r1a', 36, 27, 18, 15, 10, 4),
  },
  {
    id: 'dcs-r1-b',
    projectId: 'data-center-saclay',
    name: 'R+1B',
    floor: 'R+1',
    floorOrder: 1,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'dcs-r1-c',
    projectId: 'data-center-saclay',
    name: 'R+1C',
    floor: 'R+1',
    floorOrder: 1,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'dcs-r2',
    projectId: 'data-center-saclay',
    name: 'R+2',
    floor: 'R+2',
    floorOrder: 2,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'dcs-r3',
    projectId: 'data-center-saclay',
    name: 'R+3',
    floor: 'R+3',
    floorOrder: 3,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
  {
    id: 'dcs-toiture',
    projectId: 'data-center-saclay',
    name: 'Toiture',
    floor: 'Toiture',
    floorOrder: 999,
    status: 'en_attente',
    totalLinear: 0,
    networkGroups: [],
  },
]

export const PROCESSING_STEPS = [
  { label: 'Conversion du PDF en images haute résolution', duration: 800 },
  { label: "Détection de l'échelle dans le cartouche", duration: 600 },
  { label: "Analyse Computer Vision — réseaux EC/EF", duration: 1200 },
  { label: "Détection des gaines et systèmes CVC", duration: 1000 },
  { label: 'Comptage des équipements et ventilateurs', duration: 700 },
  { label: 'Calcul des métrés linéaires par diamètre', duration: 500 },
  { label: 'Génération du rapport de confiance', duration: 400 },
]
